hourSalary = input("Wat verdien je per uur?")
hourWorked = input("Hoeveel uur heb je gewerkt?")
salary = float(hourWorked) * float(hourSalary)
print(hourWorked + " uur werken levert " + str(salary) + " op")
print("Git tester")